(defun DEL (N LST)
   (cond ((eq N 1) (CDR LST))
      (T (cons (car LST) ( DEL (- N 1) (CDR LST) ) ) )
   )
)
(defun input ()
    (print "Исходный список:") (print LIST)
    (print "Введите место удаления:") (set 'P (read))
    (print "Итоговый список:") (set 'LIST( DEL P LIST ))    
)
(set 'LIST '(15 3 12 67 0 33 21 11))
(input)